---
title: "MSc thesis (2025-2026) - Introduction of the Unitary Patent"
---

## Project at a glance
- **Project date:** Fall 2025 - Summer 2026 (ongoing)

- **Research question:** Are granted European patents with unitary effect more likely to be validated in non-unitary European countries than comparable patents without unitary effect?

- **Methodology:** translating relational databases into a comprehensive dataset, using econometric methods such as matching to construct treatment and control groups and testing outcomes.

- **Programs used:** SQL (PATSTAT platform), R, LaTeX 

- **Output:** Preliminary results involve signs of complementarity between the choice for unitary effect and simultaneous validation in specific non-unitary European countries such as Spain and Poland. While there seems to be intitial evidence of a crowding-out of validations in Great Britain, this can be explained by applicant structure in the initial dataset.

- **Relevance:** Conducting econometrically justifyable industry analysis, useful not only for economic research (policy evaluation of the Unitary Patent), but for business purposes as well (Unitary Patent characteristics, gaps in innovation, litigation outcomes likelihood). The preliminary results are already relevant for patent attorneys and applicants, as they provide insights into the characteristics of patents that are generally more likely to be validated with unitary effect and additional non-unitary EPC-related destinations. 

