---
title: "BSc thesis (2022) - Webscraping and Sentiment Analysis"
---

## Project at a glance
- Project date: Spring 2022 (grade: 8.5 out of 10)

- Research question: How can high-frequency sentiment on twitter be used to predict the U.S. consumer sentiment index?

- Methodology: Webscraping, data cleaning, sentiment analysis, standard econometric analysis

- Programs used: Python, Stata

- Output: A dataframe containing daily, weekly and monthly twitter sentiment on macroeconomic topics such as inflation and unemployment, an econometric model regressing the U.S. consumer sentiment index on these predictors and lagged variants. 

- Relevance: This thesis shows my interest in working with self-gathered big data, and transforming it into useful aggregates to be used for further analysis. I a world that is becoming more and more data-driven, I am not afraid to think out of the box in order to increase precision and efficiency of estimates (or in this case, obtain a real-time consumer sentiment estimate instead of a lagged survey indicator).

